spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestSQL
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:/sql/createTable.sql
      encoding: UTF-8
      mode: embedded